### ISSUE TITLE
Npm test failing

### ISSUE THREAD

**Issue by leopucci** [kevoj/nodetomic-api-swagger#13]
Hi again :)

I am trying to run the npm test command but it it not working. 

I wondered if I had to run the npm start in other shell while running the npm test but it does not worked either. 

Also, how can I generate the swagger docs? 
Thanks again
Pucci

`   /api/example/greeting should return 201 (Create):
     Uncaught Error: Error: connect ECONNREFUSED 127.0.0.1:8000
      at Request._callback (test/index.js:35:5)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.onRequestError (node_modules/request/request.js:877:8)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:91:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)
`

` 11) /
       /auth/logout should return 200 (Logout):
     Uncaught Error: Error: connect ECONNREFUSED 127.0.0.1:8000
      at Request._callback (test/index.js:184:5)
      at self.callback (node_modules/request/request.js:185:22)
      at Request.onRequestError (node_modules/request/request.js:877:8)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:91:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by leopucci** [comment]
Aso there is a github clientId and secret in the config file, 
Maybe it is yours.. just to let you know

**Comment by leopucci** [comment]
I have disabled the firewall and changed the "localhost" on the config file. Didn´t worked either

**Comment by leopucci** [comment]
in fact the npm start is not working properly. It is not opening ports, so despite that the database is working. Nothing else is. 

`

┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
===============================================================================
--- PM2 development mode ------------------------------------------------------
Apps started         : app-dev
Processes started    : 1
Watch and Restart    : Enabled
Ignored folder       : node_modules
===============================================================================
app-dev-0  | (node:13109) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
app-dev-0  | -------
app-dev-0  | MongoDB-> connected on mongodb://localhost:27017/pubshare-dev
app-dev-0  | -------
`

**Comment by leopucci** [comment]
Forget about it, I was running without redis.
Now it is working ok. 
Can you give me a hint about the swaggger generation?
Thanks
Pucci

**Comment by leopucci** [comment]
Forget about it. 
I thought it was generated but it is static. 
Thanks
Pucci
